name: EAS build development

on:
  workflow_dispatch:

jobs:
  build:
    name: Development
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build on EAS development
        run: eas build -p android -e development --non-interactive
